const { withAppBuildGradle } = require("expo/config-plugins");

// Optional release signing for CI (see .github/workflows/android-build.yml).
// android/app/build.gradle is regenerated by `expo prebuild` on every run
// (it's gitignored, per the CNG workflow this project uses), so release
// signing can't just be hand-edited once — it has to be injected here.
// Activates only when CI supplies these as Gradle project properties
// (ORG_GRADLE_PROJECT_BEACON_RELEASE_* env vars); otherwise this is a
// no-op and release keeps falling back to the debug signingConfig the
// stock template sets up, unchanged.
//
// Known fragility: this assumes the generated file is Groovy
// (android/app/build.gradle), not Kotlin DSL (build.gradle.kts). If a
// future Expo/RN template migrates to .kts, this plugin's string-append
// silently stops matching and needs to be rewritten for Kotlin syntax.
const SIGNING_BLOCK = `
// --- Injected by plugins/withAndroidReleaseSigning.js ---
if (project.hasProperty('BEACON_RELEASE_STORE_FILE')) {
    android {
        signingConfigs {
            release {
                storeFile file(BEACON_RELEASE_STORE_FILE)
                storePassword BEACON_RELEASE_STORE_PASSWORD
                keyAlias BEACON_RELEASE_KEY_ALIAS
                keyPassword BEACON_RELEASE_KEY_PASSWORD
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
}
`;

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (!config.modResults.contents.includes("BEACON_RELEASE_STORE_FILE")) {
      config.modResults.contents += SIGNING_BLOCK;
    }
    return config;
  });
};
